"""Code templates for Arduino projects"""

LED_BLINK_TEMPLATE = """// LED Blink - Generated by Arduino MCP Server
// Board: {{ board_fqbn }}
// Pin: {{ pin }}

const int LED_PIN = {{ pin }};

void setup() {
  pinMode(LED_PIN, OUTPUT);
  {% if serial_enabled %}
  Serial.begin({{ serial_baud }});
  Serial.println("LED Blink Started");
  Serial.println("Pin: {{ pin }}");
  Serial.println("Interval: {{ interval }}ms");
  {% endif %}
}

void loop() {
  digitalWrite(LED_PIN, HIGH);
  {% if serial_enabled %}
  Serial.println("LED ON");
  {% endif %}
  delay({{ interval }});
  
  digitalWrite(LED_PIN, LOW);
  {% if serial_enabled %}
  Serial.println("LED OFF");
  {% endif %}
  delay({{ interval }});
}
"""

BUTTON_LED_TEMPLATE = """// Button LED Control - Generated by Arduino MCP Server
// Board: {{ board_fqbn }}
// Button Pin: {{ button_pin }}
// LED Pin: {{ led_pin }}

const int BUTTON_PIN = {{ button_pin }};
const int LED_PIN = {{ led_pin }};

void setup() {
  pinMode(BUTTON_PIN, INPUT_PULLUP);
  pinMode(LED_PIN, OUTPUT);
  {% if serial_enabled %}
  Serial.begin({{ serial_baud }});
  Serial.println("Button LED Control Started");
  {% endif %}
}

void loop() {
  int buttonState = digitalRead(BUTTON_PIN);
  
  if (buttonState == LOW) {
    digitalWrite(LED_PIN, HIGH);
    {% if serial_enabled %}
    Serial.println("Button Pressed - LED ON");
    {% endif %}
  } else {
    digitalWrite(LED_PIN, LOW);
  }
  
  delay(50);  // Debounce
}
"""


def get_template(template_name: str) -> str:
    """Get template by name"""
    templates = {
        "led_blink": LED_BLINK_TEMPLATE,
        "button_led": BUTTON_LED_TEMPLATE,
    }
    return templates.get(template_name, LED_BLINK_TEMPLATE)
